//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Venta.ServicePresentacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePresentacion.IService_Presentacion")]
    public interface IService_Presentacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Presentacion/Mostrar", ReplyAction="http://tempuri.org/IService_Presentacion/MostrarResponse")]
        System.Data.DataTable Mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Presentacion/Mostrar", ReplyAction="http://tempuri.org/IService_Presentacion/MostrarResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_PresentacionChannel : Cliente_Venta.ServicePresentacion.IService_Presentacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_PresentacionClient : System.ServiceModel.ClientBase<Cliente_Venta.ServicePresentacion.IService_Presentacion>, Cliente_Venta.ServicePresentacion.IService_Presentacion {
        
        public Service_PresentacionClient() {
        }
        
        public Service_PresentacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_PresentacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_PresentacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_PresentacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Mostrar() {
            return base.Channel.Mostrar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync() {
            return base.Channel.MostrarAsync();
        }
    }
}
