//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Venta.ServiceR_Articulo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceR_Articulo.IService_Articulo")]
    public interface IService_Articulo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/Insertar", ReplyAction="http://tempuri.org/IService_Articulo/InsertarResponse")]
        string Insertar(string codigo, string nombre, string descripcion, byte[] imagen, int idcategoria, int idpresentacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/Insertar", ReplyAction="http://tempuri.org/IService_Articulo/InsertarResponse")]
        System.Threading.Tasks.Task<string> InsertarAsync(string codigo, string nombre, string descripcion, byte[] imagen, int idcategoria, int idpresentacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/Editar", ReplyAction="http://tempuri.org/IService_Articulo/EditarResponse")]
        string Editar(int idarticulo, string codigo, string nombre, string descripcion, byte[] imagen, int idcategoria, int idpresentacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/Editar", ReplyAction="http://tempuri.org/IService_Articulo/EditarResponse")]
        System.Threading.Tasks.Task<string> EditarAsync(int idarticulo, string codigo, string nombre, string descripcion, byte[] imagen, int idcategoria, int idpresentacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/Eliminar", ReplyAction="http://tempuri.org/IService_Articulo/EliminarResponse")]
        string Eliminar(int idarticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/Eliminar", ReplyAction="http://tempuri.org/IService_Articulo/EliminarResponse")]
        System.Threading.Tasks.Task<string> EliminarAsync(int idarticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/Mostrar", ReplyAction="http://tempuri.org/IService_Articulo/MostrarResponse")]
        System.Data.DataTable Mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/Mostrar", ReplyAction="http://tempuri.org/IService_Articulo/MostrarResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/BuscarNombre", ReplyAction="http://tempuri.org/IService_Articulo/BuscarNombreResponse")]
        System.Data.DataTable BuscarNombre(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/BuscarNombre", ReplyAction="http://tempuri.org/IService_Articulo/BuscarNombreResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarNombreAsync(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/Stock_Articulos", ReplyAction="http://tempuri.org/IService_Articulo/Stock_ArticulosResponse")]
        System.Data.DataTable Stock_Articulos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Articulo/Stock_Articulos", ReplyAction="http://tempuri.org/IService_Articulo/Stock_ArticulosResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Stock_ArticulosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_ArticuloChannel : Cliente_Venta.ServiceR_Articulo.IService_Articulo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_ArticuloClient : System.ServiceModel.ClientBase<Cliente_Venta.ServiceR_Articulo.IService_Articulo>, Cliente_Venta.ServiceR_Articulo.IService_Articulo {
        
        public Service_ArticuloClient() {
        }
        
        public Service_ArticuloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_ArticuloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_ArticuloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_ArticuloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Insertar(string codigo, string nombre, string descripcion, byte[] imagen, int idcategoria, int idpresentacion) {
            return base.Channel.Insertar(codigo, nombre, descripcion, imagen, idcategoria, idpresentacion);
        }
        
        public System.Threading.Tasks.Task<string> InsertarAsync(string codigo, string nombre, string descripcion, byte[] imagen, int idcategoria, int idpresentacion) {
            return base.Channel.InsertarAsync(codigo, nombre, descripcion, imagen, idcategoria, idpresentacion);
        }
        
        public string Editar(int idarticulo, string codigo, string nombre, string descripcion, byte[] imagen, int idcategoria, int idpresentacion) {
            return base.Channel.Editar(idarticulo, codigo, nombre, descripcion, imagen, idcategoria, idpresentacion);
        }
        
        public System.Threading.Tasks.Task<string> EditarAsync(int idarticulo, string codigo, string nombre, string descripcion, byte[] imagen, int idcategoria, int idpresentacion) {
            return base.Channel.EditarAsync(idarticulo, codigo, nombre, descripcion, imagen, idcategoria, idpresentacion);
        }
        
        public string Eliminar(int idarticulo) {
            return base.Channel.Eliminar(idarticulo);
        }
        
        public System.Threading.Tasks.Task<string> EliminarAsync(int idarticulo) {
            return base.Channel.EliminarAsync(idarticulo);
        }
        
        public System.Data.DataTable Mostrar() {
            return base.Channel.Mostrar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync() {
            return base.Channel.MostrarAsync();
        }
        
        public System.Data.DataTable BuscarNombre(string textobuscar) {
            return base.Channel.BuscarNombre(textobuscar);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarNombreAsync(string textobuscar) {
            return base.Channel.BuscarNombreAsync(textobuscar);
        }
        
        public System.Data.DataTable Stock_Articulos() {
            return base.Channel.Stock_Articulos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Stock_ArticulosAsync() {
            return base.Channel.Stock_ArticulosAsync();
        }
    }
}
