//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Venta.ServiceProveedor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProveedor.IService_Proveedor")]
    public interface IService_Proveedor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/Insertar", ReplyAction="http://tempuri.org/IService_Proveedor/InsertarResponse")]
        string Insertar(string razon_proveedor, string sector_comercial, string tipo_documento, string num_documento, string direccion, string telefono, string email, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/Insertar", ReplyAction="http://tempuri.org/IService_Proveedor/InsertarResponse")]
        System.Threading.Tasks.Task<string> InsertarAsync(string razon_proveedor, string sector_comercial, string tipo_documento, string num_documento, string direccion, string telefono, string email, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/Editar", ReplyAction="http://tempuri.org/IService_Proveedor/EditarResponse")]
        string Editar(int iD_Proveedor, string razon_proveedor, string sector_comercial, string tipo_documento, string num_documento, string direccion, string telefono, string email, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/Editar", ReplyAction="http://tempuri.org/IService_Proveedor/EditarResponse")]
        System.Threading.Tasks.Task<string> EditarAsync(int iD_Proveedor, string razon_proveedor, string sector_comercial, string tipo_documento, string num_documento, string direccion, string telefono, string email, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/Eliminar", ReplyAction="http://tempuri.org/IService_Proveedor/EliminarResponse")]
        string Eliminar(int iD_Proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/Eliminar", ReplyAction="http://tempuri.org/IService_Proveedor/EliminarResponse")]
        System.Threading.Tasks.Task<string> EliminarAsync(int iD_Proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/Mostrar", ReplyAction="http://tempuri.org/IService_Proveedor/MostrarResponse")]
        System.Data.DataTable Mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/Mostrar", ReplyAction="http://tempuri.org/IService_Proveedor/MostrarResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/BuscarRazon_social", ReplyAction="http://tempuri.org/IService_Proveedor/BuscarRazon_socialResponse")]
        System.Data.DataTable BuscarRazon_social(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/BuscarRazon_social", ReplyAction="http://tempuri.org/IService_Proveedor/BuscarRazon_socialResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarRazon_socialAsync(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/BuscarNum_Documento", ReplyAction="http://tempuri.org/IService_Proveedor/BuscarNum_DocumentoResponse")]
        System.Data.DataTable BuscarNum_Documento(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Proveedor/BuscarNum_Documento", ReplyAction="http://tempuri.org/IService_Proveedor/BuscarNum_DocumentoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarNum_DocumentoAsync(string textobuscar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_ProveedorChannel : Cliente_Venta.ServiceProveedor.IService_Proveedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_ProveedorClient : System.ServiceModel.ClientBase<Cliente_Venta.ServiceProveedor.IService_Proveedor>, Cliente_Venta.ServiceProveedor.IService_Proveedor {
        
        public Service_ProveedorClient() {
        }
        
        public Service_ProveedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_ProveedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_ProveedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_ProveedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Insertar(string razon_proveedor, string sector_comercial, string tipo_documento, string num_documento, string direccion, string telefono, string email, string url) {
            return base.Channel.Insertar(razon_proveedor, sector_comercial, tipo_documento, num_documento, direccion, telefono, email, url);
        }
        
        public System.Threading.Tasks.Task<string> InsertarAsync(string razon_proveedor, string sector_comercial, string tipo_documento, string num_documento, string direccion, string telefono, string email, string url) {
            return base.Channel.InsertarAsync(razon_proveedor, sector_comercial, tipo_documento, num_documento, direccion, telefono, email, url);
        }
        
        public string Editar(int iD_Proveedor, string razon_proveedor, string sector_comercial, string tipo_documento, string num_documento, string direccion, string telefono, string email, string url) {
            return base.Channel.Editar(iD_Proveedor, razon_proveedor, sector_comercial, tipo_documento, num_documento, direccion, telefono, email, url);
        }
        
        public System.Threading.Tasks.Task<string> EditarAsync(int iD_Proveedor, string razon_proveedor, string sector_comercial, string tipo_documento, string num_documento, string direccion, string telefono, string email, string url) {
            return base.Channel.EditarAsync(iD_Proveedor, razon_proveedor, sector_comercial, tipo_documento, num_documento, direccion, telefono, email, url);
        }
        
        public string Eliminar(int iD_Proveedor) {
            return base.Channel.Eliminar(iD_Proveedor);
        }
        
        public System.Threading.Tasks.Task<string> EliminarAsync(int iD_Proveedor) {
            return base.Channel.EliminarAsync(iD_Proveedor);
        }
        
        public System.Data.DataTable Mostrar() {
            return base.Channel.Mostrar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync() {
            return base.Channel.MostrarAsync();
        }
        
        public System.Data.DataTable BuscarRazon_social(string textobuscar) {
            return base.Channel.BuscarRazon_social(textobuscar);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarRazon_socialAsync(string textobuscar) {
            return base.Channel.BuscarRazon_socialAsync(textobuscar);
        }
        
        public System.Data.DataTable BuscarNum_Documento(string textobuscar) {
            return base.Channel.BuscarNum_Documento(textobuscar);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarNum_DocumentoAsync(string textobuscar) {
            return base.Channel.BuscarNum_DocumentoAsync(textobuscar);
        }
    }
}
