//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Venta.ServiceCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCliente.IService_Cliente")]
    public interface IService_Cliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Cliente/Mostrar", ReplyAction="http://tempuri.org/IService_Cliente/MostrarResponse")]
        System.Data.DataTable Mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Cliente/Mostrar", ReplyAction="http://tempuri.org/IService_Cliente/MostrarResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Cliente/BuscarApellidos", ReplyAction="http://tempuri.org/IService_Cliente/BuscarApellidosResponse")]
        System.Data.DataTable BuscarApellidos(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Cliente/BuscarApellidos", ReplyAction="http://tempuri.org/IService_Cliente/BuscarApellidosResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarApellidosAsync(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Cliente/BuscarNum_Documento", ReplyAction="http://tempuri.org/IService_Cliente/BuscarNum_DocumentoResponse")]
        System.Data.DataTable BuscarNum_Documento(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Cliente/BuscarNum_Documento", ReplyAction="http://tempuri.org/IService_Cliente/BuscarNum_DocumentoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarNum_DocumentoAsync(string textobuscar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_ClienteChannel : Cliente_Venta.ServiceCliente.IService_Cliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_ClienteClient : System.ServiceModel.ClientBase<Cliente_Venta.ServiceCliente.IService_Cliente>, Cliente_Venta.ServiceCliente.IService_Cliente {
        
        public Service_ClienteClient() {
        }
        
        public Service_ClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_ClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_ClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_ClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Mostrar() {
            return base.Channel.Mostrar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync() {
            return base.Channel.MostrarAsync();
        }
        
        public System.Data.DataTable BuscarApellidos(string textobuscar) {
            return base.Channel.BuscarApellidos(textobuscar);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarApellidosAsync(string textobuscar) {
            return base.Channel.BuscarApellidosAsync(textobuscar);
        }
        
        public System.Data.DataTable BuscarNum_Documento(string textobuscar) {
            return base.Channel.BuscarNum_Documento(textobuscar);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarNum_DocumentoAsync(string textobuscar) {
            return base.Channel.BuscarNum_DocumentoAsync(textobuscar);
        }
    }
}
