//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Venta.ServiceCategoria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCategoria.IService_Categoria")]
    public interface IService_Categoria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Categoria/Mostrar", ReplyAction="http://tempuri.org/IService_Categoria/MostrarResponse")]
        System.Data.DataTable Mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Categoria/Mostrar", ReplyAction="http://tempuri.org/IService_Categoria/MostrarResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Categoria/BuscarNombre", ReplyAction="http://tempuri.org/IService_Categoria/BuscarNombreResponse")]
        System.Data.DataTable BuscarNombre(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Categoria/BuscarNombre", ReplyAction="http://tempuri.org/IService_Categoria/BuscarNombreResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarNombreAsync(string textobuscar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_CategoriaChannel : Cliente_Venta.ServiceCategoria.IService_Categoria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_CategoriaClient : System.ServiceModel.ClientBase<Cliente_Venta.ServiceCategoria.IService_Categoria>, Cliente_Venta.ServiceCategoria.IService_Categoria {
        
        public Service_CategoriaClient() {
        }
        
        public Service_CategoriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_CategoriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_CategoriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_CategoriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Mostrar() {
            return base.Channel.Mostrar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync() {
            return base.Channel.MostrarAsync();
        }
        
        public System.Data.DataTable BuscarNombre(string textobuscar) {
            return base.Channel.BuscarNombre(textobuscar);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarNombreAsync(string textobuscar) {
            return base.Channel.BuscarNombreAsync(textobuscar);
        }
    }
}
