//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Venta.ServiceVenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVenta.IService_Venta")]
    public interface IService_Venta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/Insertar", ReplyAction="http://tempuri.org/IService_Venta/InsertarResponse")]
        string Insertar(int idcliente, int idtrabajador, System.DateTime fecha, string tipo_comprobante, string serie, string correlativo, decimal igv, System.Data.DataTable dtDetalles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/Insertar", ReplyAction="http://tempuri.org/IService_Venta/InsertarResponse")]
        System.Threading.Tasks.Task<string> InsertarAsync(int idcliente, int idtrabajador, System.DateTime fecha, string tipo_comprobante, string serie, string correlativo, decimal igv, System.Data.DataTable dtDetalles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/Eliminar", ReplyAction="http://tempuri.org/IService_Venta/EliminarResponse")]
        string Eliminar(int iD_Venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/Eliminar", ReplyAction="http://tempuri.org/IService_Venta/EliminarResponse")]
        System.Threading.Tasks.Task<string> EliminarAsync(int iD_Venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/Mostrar", ReplyAction="http://tempuri.org/IService_Venta/MostrarResponse")]
        System.Data.DataTable Mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/Mostrar", ReplyAction="http://tempuri.org/IService_Venta/MostrarResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/BuscarFechas", ReplyAction="http://tempuri.org/IService_Venta/BuscarFechasResponse")]
        System.Data.DataTable BuscarFechas(string textobuscar, string textobuscar2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/BuscarFechas", ReplyAction="http://tempuri.org/IService_Venta/BuscarFechasResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarFechasAsync(string textobuscar, string textobuscar2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/MostrarDetalle", ReplyAction="http://tempuri.org/IService_Venta/MostrarDetalleResponse")]
        System.Data.DataTable MostrarDetalle(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/MostrarDetalle", ReplyAction="http://tempuri.org/IService_Venta/MostrarDetalleResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarDetalleAsync(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/MostrarArticulo_Venta_Nombre", ReplyAction="http://tempuri.org/IService_Venta/MostrarArticulo_Venta_NombreResponse")]
        System.Data.DataTable MostrarArticulo_Venta_Nombre(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/MostrarArticulo_Venta_Nombre", ReplyAction="http://tempuri.org/IService_Venta/MostrarArticulo_Venta_NombreResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarArticulo_Venta_NombreAsync(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/MostrarArticulo_Venta_Codigo", ReplyAction="http://tempuri.org/IService_Venta/MostrarArticulo_Venta_CodigoResponse")]
        System.Data.DataTable MostrarArticulo_Venta_Codigo(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/MostrarArticulo_Venta_Codigo", ReplyAction="http://tempuri.org/IService_Venta/MostrarArticulo_Venta_CodigoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarArticulo_Venta_CodigoAsync(string textobuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/MostrarArticulo_Venta", ReplyAction="http://tempuri.org/IService_Venta/MostrarArticulo_VentaResponse")]
        System.Data.DataTable MostrarArticulo_Venta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_Venta/MostrarArticulo_Venta", ReplyAction="http://tempuri.org/IService_Venta/MostrarArticulo_VentaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostrarArticulo_VentaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_VentaChannel : Cliente_Venta.ServiceVenta.IService_Venta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_VentaClient : System.ServiceModel.ClientBase<Cliente_Venta.ServiceVenta.IService_Venta>, Cliente_Venta.ServiceVenta.IService_Venta {
        
        public Service_VentaClient() {
        }
        
        public Service_VentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_VentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_VentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_VentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Insertar(int idcliente, int idtrabajador, System.DateTime fecha, string tipo_comprobante, string serie, string correlativo, decimal igv, System.Data.DataTable dtDetalles) {
            return base.Channel.Insertar(idcliente, idtrabajador, fecha, tipo_comprobante, serie, correlativo, igv, dtDetalles);
        }
        
        public System.Threading.Tasks.Task<string> InsertarAsync(int idcliente, int idtrabajador, System.DateTime fecha, string tipo_comprobante, string serie, string correlativo, decimal igv, System.Data.DataTable dtDetalles) {
            return base.Channel.InsertarAsync(idcliente, idtrabajador, fecha, tipo_comprobante, serie, correlativo, igv, dtDetalles);
        }
        
        public string Eliminar(int iD_Venta) {
            return base.Channel.Eliminar(iD_Venta);
        }
        
        public System.Threading.Tasks.Task<string> EliminarAsync(int iD_Venta) {
            return base.Channel.EliminarAsync(iD_Venta);
        }
        
        public System.Data.DataTable Mostrar() {
            return base.Channel.Mostrar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarAsync() {
            return base.Channel.MostrarAsync();
        }
        
        public System.Data.DataTable BuscarFechas(string textobuscar, string textobuscar2) {
            return base.Channel.BuscarFechas(textobuscar, textobuscar2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarFechasAsync(string textobuscar, string textobuscar2) {
            return base.Channel.BuscarFechasAsync(textobuscar, textobuscar2);
        }
        
        public System.Data.DataTable MostrarDetalle(string textobuscar) {
            return base.Channel.MostrarDetalle(textobuscar);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarDetalleAsync(string textobuscar) {
            return base.Channel.MostrarDetalleAsync(textobuscar);
        }
        
        public System.Data.DataTable MostrarArticulo_Venta_Nombre(string textobuscar) {
            return base.Channel.MostrarArticulo_Venta_Nombre(textobuscar);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarArticulo_Venta_NombreAsync(string textobuscar) {
            return base.Channel.MostrarArticulo_Venta_NombreAsync(textobuscar);
        }
        
        public System.Data.DataTable MostrarArticulo_Venta_Codigo(string textobuscar) {
            return base.Channel.MostrarArticulo_Venta_Codigo(textobuscar);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarArticulo_Venta_CodigoAsync(string textobuscar) {
            return base.Channel.MostrarArticulo_Venta_CodigoAsync(textobuscar);
        }
        
        public System.Data.DataTable MostrarArticulo_Venta() {
            return base.Channel.MostrarArticulo_Venta();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostrarArticulo_VentaAsync() {
            return base.Channel.MostrarArticulo_VentaAsync();
        }
    }
}
